// ─── Psychometric PDF Template ────────────────────────────────────────────────

import { PDF_CSS } from './styles';
import {
  buildHorizontalBarChart,
  buildVerticalBarChart,
  buildRadarChart,
  scoreColors,
  PALETTE,
} from './chartBuilder';
import type { PsychometricReport } from '@/lib/scoring/types';

function formatText(text: string | null | undefined): string {
  if (!text) return '';
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/\\*\\*(.*?)\\*\\*/g, '<strong>$1</strong>')
    .replace(/\\n/g, '<br/>');
}

function fitClass(fit: string): string {
  if (fit === 'Strong Fit')   return 'fit-strong';
  if (fit === 'Good Fit')     return 'fit-good';
  if (fit === 'Possible Fit') return 'fit-possible';
  return 'fit-low';
}

function bandBar(score: number): string {
  let color = '#dc2626';
  if (score >= 75) color = '#16a34a';
  else if (score >= 55) color = '#2563eb';
  else if (score >= 40) color = '#f59e0b';
  return color;
}

function bandPill(band: string): string {
  switch (band) {
    case 'Strong Preference': return 'background:#1d4ed8;color:#fff;';
    case 'Clear Preference':  return 'background:#dbeafe;color:#1e40af;';
    case 'Balanced':          return 'background:#f1f5f9;color:#374151;';
    default:                  return 'background:#fef9c3;color:#713f12;';
  }
}

function confidencePill(level: string): string {
  if (level === 'High')     return 'background:#d1fae5;color:#065f46;';
  if (level === 'Moderate') return 'background:#fef3c7;color:#92400e;';
  return 'background:#fee2e2;color:#991b1b;';
}

export async function buildPsychometricTemplate(
  report: PsychometricReport,
  candidateName: string,
  date: string
): Promise<string> {
  // ── Work-Style Bar Chart ──
  const wsItems = report.work_style_profile || [];
  const wsLabels = wsItems.map(i => i.construct);
  const wsValues = wsItems.map(i => i.normalized);
  const wsColors = scoreColors(wsValues);
  const wsChart   = wsItems.length
    ? buildHorizontalBarChart(wsLabels, wsValues, wsColors)
    : null;

  // ── RIASEC Radar Chart ──
  const riasecEntries = Object.entries(report.interest_profile || {});
  const riasecChart = riasecEntries.length
    ? buildRadarChart(riasecEntries.map(([k]) => k), riasecEntries.map(([, v]) => v))
    : null;

  // ── Domain Score Chart ──
  const domains = report.top_career_domains || [];
  const domainChart = domains.length
    ? buildVerticalBarChart(
        domains.map(d => d.domain.split(' ')[0]),
        domains.map(d => d.score),
        scoreColors(domains.map(d => d.score))
      )
    : null;

  const disclaimer = `This report is generated by an automated assessment engine for career guidance purposes only.
    Results should be interpreted by a qualified career counsellor in context. Scores are indicative
    and do not constitute a definitive evaluation of ability or character.`;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Psychometric Career Report — ${candidateName}</title>
  <style>${PDF_CSS}</style>
</head>
<body>

<!-- ═══════════════════ COVER PAGE ═══════════════════ -->
<div class="page cover">
  <div>
    <div class="cover-logo">Omkar Career Counseling</div>
    <div class="cover-title">Psychometric<br/>Career Report</div>
    <div class="cover-sub">Career Preferences, Interests &amp; Work-Style Analysis</div>
    <span class="cover-badge">Counselling-Grade Engine</span>
    <span class="cover-badge">RIASEC + Work-Style</span>
    <span class="cover-badge">v2.0</span>
  </div>
  <div>
    <div class="cover-name">${candidateName}</div>
    <div class="cover-date">Generated: ${date}</div>

    ${report.holland_code ? `
    <div style="margin:18px 0;background:rgba(255,255,255,0.12);border:1.5px solid rgba(255,255,255,0.3);border-radius:12px;padding:16px 20px;">
      <div style="font-size:9px;font-weight:800;color:rgba(255,255,255,0.6);text-transform:uppercase;letter-spacing:0.12em;margin-bottom:6px;">Holland Code (RIASEC)</div>
      <div style="font-size:22px;font-weight:900;color:#fff;letter-spacing:0.05em;margin-bottom:6px;">${report.holland_code}</div>
      <div style="font-size:11.5px;color:rgba(255,255,255,0.85);line-height:1.55;font-style:italic;">${report.holland_description}</div>
    </div>` : ''}

    <div class="cover-footer">
      Confidence Level: <strong>${report.confidence_level || '—'}</strong> &nbsp;|&nbsp;
      Response Reliability: <strong>${report.reliability_flag || '—'}</strong>
    </div>
  </div>
</div>

<!-- ═══════════════════ PAGE 1: SUMMARY + WORK-STYLE ═══════════════════ -->
<div class="page">
  <div class="page-header">
    <span class="page-org">Omkar Career Counseling</span>
    <span class="page-type">Psychometric Report</span>
  </div>

  <!-- Career Orientation Summary -->
  <div class="section-header">
    <div class="section-dot" style="background:#2563eb;"></div>
    <span class="section-title">Career Orientation Summary</span>
  </div>

  <!-- Key Findings at a Glance -->
  <div class="glance-box">
    <div class="glance-header">
      <div class="glance-header-dot"></div>
      <span class="glance-header-title">Key Findings at a Glance</span>
    </div>
    <div class="glance-body">
      ${report.holland_code ? `<div class="glance-item"><span class="glance-bullet">1</span><span><strong>Holland Code:</strong> ${report.holland_code}</span></div>` : ''}
      ${wsItems.length > 0 ? `<div class="glance-item"><span class="glance-bullet">2</span><span><strong>Top work-style trait:</strong> ${wsItems[0].construct} &mdash; ${wsItems[0].normalized}% (${wsItems[0].band})</span></div>` : ''}
      ${report.contradiction_note ? `<div class="glance-item"><span class="glance-bullet">3</span><span><strong>Behavioural note:</strong> ${report.contradiction_note}</span></div>` : ''}
      ${report.midpoint_bias ? `<div class="glance-item"><span class="glance-bullet">!</span><span><strong>Response pattern:</strong> High proportion of neutral responses noted &mdash; discuss with candidate before drawing conclusions.</span></div>` : ''}
    </div>
  </div>

  <div class="card-highlight">
    <p style="color:#fff;font-weight:500;font-size:12.5px;line-height:1.8;white-space:pre-line;">${formatText(report.career_orientation_summary) || '&mdash;'}</p>
  </div>

  ${report.primary_gap_insight ? `
  <div class="insight-box">
    <div class="insight-label">&#x26A1; Key Observation</div>
    <div class="insight-text">${formatText(report.primary_gap_insight)}</div>
  </div>` : ''}

  ${report.contradiction_note ? `
  <div class="conflict-box">
    <div class="conflict-label">&#x1F500; Behavioural Insight</div>
    <p style="font-size:11.5px;color:#3730a3;font-weight:500;">${formatText(report.contradiction_note)}</p>
  </div>` : ''}

  <!-- Work-Style Profile -->
  <div class="section-header" style="margin-top:18px;">
    <div class="section-dot" style="background:#7c3aed;"></div>
    <span class="section-title">Work-Style Profile</span>
    <span class="section-subtitle">8 Work-Style Dimensions</span>
  </div>

  <p class="plain-intro">The following dimensions reflect how ${candidateName} tends to approach their work &mdash; these are preference patterns, not fixed personality traits.</p>

  ${wsChart ? `<img class="chart-img" src="${wsChart}" />` : wsItems.map(item => `
  <div class="bar-row">
    <div class="bar-label">${item.construct}</div>
    <div class="bar-track">
      <div class="bar-fill" style="width:${item.normalized}%;background:${bandBar(item.normalized)};"></div>
    </div>
    <div class="bar-value">${item.normalized}%</div>
    <div class="bar-band" style="${bandPill(item.band)}">${item.band}</div>
  </div>`).join('')}

  <div class="page-footer">
    <span>Psychometric Career Report — ${candidateName}</span>
    <span>${date}</span>
  </div>
</div>

<!-- ═══════════════════ PAGE 2: RIASEC + DOMAINS ═══════════════════ -->
<div class="page">
  <div class="page-header">
    <span class="page-org">Omkar Career Counseling</span>
    <span class="page-type">Interest &amp; Domain Fit</span>
  </div>

  <!-- RIASEC Interest Profile -->
  <div class="section-header">
    <div class="section-dot" style="background:#0d9488;"></div>
    <span class="section-title">Interest Profile (RIASEC)</span>
    <span class="section-subtitle">Career Interest Dimensions</span>
  </div>

  <p class="plain-intro">RIASEC is a widely-used framework for understanding vocational interests. The following scores indicate which types of activities ${candidateName} finds most engaging. Higher scores suggest stronger alignment with that category's typical work environment.</p>

  <div style="display:flex;gap:20px;align-items:flex-start;margin-bottom:16px;">
    ${riasecChart ? `<img class="chart-img" style="width:260px;" src="${riasecChart}" />` : ''}
    <div style="flex:1;">
      ${riasecEntries.map(([name, score], idx) => `
      <div class="bar-row">
        <div class="bar-label" style="width:100px;">${name}</div>
        <div class="bar-track">
          <div class="bar-fill" style="width:${score}%;background:${PALETTE[idx % PALETTE.length]};"></div>
        </div>
        <div class="bar-value">${score}%</div>
      </div>`).join('')}
    </div>
  </div>

  <!-- Career Domain Fit -->
  <div class="section-header" style="margin-top:18px;">
    <div class="section-dot" style="background:#16a34a;"></div>
    <span class="section-title">Career Domain Fit</span>
    <span class="section-subtitle">Psychometric Alignment</span>
  </div>

  <p class="plain-intro">The following career domains are ranked by psychometric fit &mdash; how well ${candidateName}'s interest and work-style profile aligns with what each domain typically demands of its practitioners.</p>

  ${domainChart ? `<img class="chart-img" style="width:100%;max-height:180px;object-fit:contain;" src="${domainChart}" />` : ''}

  ${domains.map((d, i) => `
  <div class="domain-card ${fitClass(d.fit)}">
    <div style="flex:1;">
      <div class="domain-name">#${i + 1} ${d.domain}</div>
      <div class="domain-expl">${formatText(d.explanation)}</div>
      <span class="domain-fit ${fitClass(d.fit)}">${d.fit}</span>
    </div>
    <div class="domain-score">${d.score}</div>
  </div>`).join('')}

  <div class="page-footer">
    <span>Psychometric Career Report — ${candidateName}</span>
    <span>${date}</span>
  </div>
</div>

<!-- ═══════════════════ PAGE 3: ENVIRONMENT + DEVELOPMENT + CONFIDENCE ═══════════════════ -->
<div class="page">
  <div class="page-header">
    <span class="page-org">Omkar Career Counseling</span>
    <span class="page-type">Development &amp; Confidence</span>
  </div>

  <!-- Work Environment Fit -->
  ${report.work_environment_fit ? `
  <div class="section-header">
    <div class="section-dot" style="background:#2563eb;"></div>
    <span class="section-title">Work Environment Fit</span>
  </div>
  <div style="margin-bottom:18px;">
    <div class="stat-box" style="background:#eff6ff;">
      <div class="stat-label">Work Environment Preference</div>
      <div style="color:#1d4ed8; font-size: 14px; font-weight: 500; margin-top: 6px; line-height: 1.6;">${report.work_environment_fit}</div>
    </div>
  </div>` : ''}

  <!-- Development Suggestions -->
  <div class="section-header">
    <div class="section-dot" style="background:#f59e0b;"></div>
    <span class="section-title">Development Suggestions</span>
    <span class="section-subtitle">Work-style dimensions with growth potential</span>
  </div>

  ${(report.development_suggestions || []).length === 0
    ? `<div class="card"><p style="color:#16a34a;font-weight:600;">✓ No critical development gaps identified. Strong profile across all work-style dimensions.</p></div>`
    : (report.development_suggestions || []).map(s => `
  <div class="card" style="display:flex;gap:12px;align-items:flex-start;">
    <span style="color:#f59e0b;font-size:16px;">→</span>
    <p style="font-size:11.5px;color:#374151;line-height:1.65;">${formatText(s)}</p>
  </div>`).join('')}

  <!-- Confidence & Reliability -->
  <div class="section-header" style="margin-top:18px;">
    <div class="section-dot" style="background:#6b7280;"></div>
    <span class="section-title">Assessment Quality Indicators</span>
  </div>
  <div class="grid-3" style="margin-bottom:14px;">
    <div class="stat-box">
      <div class="stat-label">Confidence Level</div>
      <div style="margin-top:6px;">
        <span class="pill" style="${confidencePill(report.confidence_level || 'Low')}">${report.confidence_level || '—'}</span>
      </div>
      <div class="stat-desc">Response engagement quality</div>
    </div>
    <div class="stat-box">
      <div class="stat-label">Reliability Flag</div>
      <div style="margin-top:6px;">
        <span class="pill" style="${report.reliability_flag === 'OK' ? 'background:#d1fae5;color:#065f46;' : 'background:#fee2e2;color:#991b1b;'}">${report.reliability_flag === 'OK' ? '✓ Verified' : '⚠ Low'}</span>
      </div>
      <div class="stat-desc">Attention check result</div>
    </div>
    <div class="stat-box">
      <div class="stat-label">Dimensions Assessed</div>
      <div class="stat-value">${wsItems.length}</div>
      <div class="stat-desc">Work-style constructs</div>
    </div>
  </div>

  ${report.midpoint_bias ? `
  <div style="background:#fffbeb;border:2px solid #f59e0b;border-radius:10px;padding:14px 18px;margin-bottom:16px;display:flex;gap:12px;align-items:flex-start;">
    <span style="font-size:20px;line-height:1;">⚠️</span>
    <div>
      <div style="font-size:11px;font-weight:800;color:#92400e;text-transform:uppercase;letter-spacing:0.08em;margin-bottom:4px;">Response Pattern Note — For Counsellor Review</div>
      <p style="font-size:12px;color:#78350f;line-height:1.6;margin:0;">A high proportion of 'Not Sure' responses were recorded in this assessment. The candidate may have answered cautiously, or may genuinely be undecided about their preferences. The counsellor should discuss these results directly with the candidate before drawing firm conclusions.</p>
    </div>
  </div>` : ''}

  <div class="disclaimer">${disclaimer}</div>

  <div class="discussion-box">
    <div class="discussion-label">Suggested Session Questions &mdash; For Counsellor Use</div>
    <div class="discussion-item"><strong>1.</strong> &ldquo;Looking at your interest profile, which of these areas have you actually had experience with &mdash; in school, at home, or in activities you enjoy?&rdquo;</div>
    <div class="discussion-item"><strong>2.</strong> &ldquo;When you imagine your ideal workday in the future, what does it feel like &mdash; working with people, with ideas, with tools, or with systems?&rdquo;</div>
    <div class="discussion-item"><strong>3.</strong> &ldquo;Are there any career domains on this list that surprised you &mdash; either higher or lower than you expected?&rdquo;</div>
  </div>

  <div class="page-footer">
    <span>Psychometric Career Report &mdash; ${candidateName}</span>
    <span>${date}</span>
  </div>
</div>

</body>
</html>`;
}
