INSERT INTO questions (id, test_id, type, question_text, options, correct_answer, image_url, mappings, cohort, category, difficulty) VALUES 
('G57_A6', '5-7', 'aptitude', 'Which is prime?', '[{"id":"opt_0","text":"4","value":0},{"id":"opt_1","text":"6","value":0},{"id":"opt_2","text":"7","value":0},{"id":"opt_3","text":"8","value":0}]', 'opt_2', NULL, '[{"trait":"analytical","weight":1}]', 'grade_5_7', 'analytical', 'medium'),
('G57_A7', '5-7', 'aptitude', 'Find next: 2, 3, 5, 8, ?', '[{"id":"opt_0","text":"11","value":0},{"id":"opt_1","text":"12","value":0},{"id":"opt_2","text":"13","value":0},{"id":"opt_3","text":"14","value":0}]', 'opt_2', NULL, '[{"trait":"analytical","weight":1}]', 'grade_5_7', 'analytical', 'medium'),
('G57_A8', '5-7', 'aptitude', 'Smallest: 0.5, 0.25, 0.75', '[{"id":"opt_0","text":"0.5","value":0},{"id":"opt_1","text":"0.25","value":0},{"id":"opt_2","text":"0.75","value":0},{"id":"opt_3","text":"None","value":0}]', 'opt_1', NULL, '[{"trait":"analytical","weight":1}]', 'grade_5_7', 'analytical', 'medium'),
('G57_A9', '5-7', 'aptitude', 'Today Friday, after 4 days?', '[{"id":"opt_0","text":"Sunday","value":0},{"id":"opt_1","text":"Monday","value":0},{"id":"opt_2","text":"Tuesday","value":0},{"id":"opt_3","text":"Wednesday","value":0}]', 'opt_2', NULL, '[{"trait":"analytical","weight":1}]', 'grade_5_7', 'analytical', 'medium'),
('G57_A10', '5-7', 'aptitude', 'If 3x = 15, x = ?', '[{"id":"opt_0","text":"3","value":0},{"id":"opt_1","text":"4","value":0},{"id":"opt_2","text":"5","value":0},{"id":"opt_3","text":"6","value":0}]', 'opt_2', NULL, '[{"trait":"analytical","weight":1}]', 'grade_5_7', 'analytical', 'medium'),
('G57_A11', '5-7', 'aptitude', 'Which number is divisible by 3?', '[{"id":"opt_0","text":"10","value":0},{"id":"opt_1","text":"12","value":0},{"id":"opt_2","text":"14","value":0},{"id":"opt_3","text":"16","value":0}]', 'opt_1', NULL, '[{"trait":"analytical","weight":1}]', 'grade_5_7', 'analytical', 'medium'),
('G57_A12', '5-7', 'aptitude', 'After Sunday comes?', '[{"id":"opt_0","text":"Monday","value":0},{"id":"opt_1","text":"Tuesday","value":0},{"id":"opt_2","text":"Saturday","value":0},{"id":"opt_3","text":"Friday","value":0}]', 'opt_0', NULL, '[{"trait":"analytical","weight":1}]', 'grade_5_7', 'analytical', 'medium'),
('G57_A13', '5-7', 'aptitude', 'Find missing: 6, 12, 18, ?', '[{"id":"opt_0","text":"20","value":0},{"id":"opt_1","text":"22","value":0},{"id":"opt_2","text":"24","value":0},{"id":"opt_3","text":"26","value":0}]', 'opt_2', NULL, '[{"trait":"analytical","weight":1}]', 'grade_5_7', 'analytical', 'medium'),
('c21be407-ce23-490f-a0a5-231ed302dcc3', '2-4', 'aptitude', 'Identify the pattern. Which shape comes next in the sequence?', '[{"id":"q1_o0","text":"/images/visual/q1_optA.svg","value":0},{"id":"q1_o1","text":"/images/visual/q1_optB.svg","value":0},{"id":"q1_o2","text":"/images/visual/q1_optC.svg","value":0},{"id":"q1_o3","text":"/images/visual/q1_optD.svg","value":0}]', 'q1_o1', '/images/visual/q1_prompt.svg', '[{"trait":"spatial","weight":1}]', 'grade_2_4', 'spatial', 'hard'),
('5b734c83-3ea8-4d13-bdd9-9e69ddd58d46', '5-7', 'aptitude', 'Analyze the 2x2 matrix. Which option logically replaces the question mark?', '[{"id":"q2_o0","text":"/images/visual/q2_optA.svg","value":0},{"id":"q2_o1","text":"/images/visual/q2_optB.svg","value":0},{"id":"q2_o2","text":"/images/visual/q2_optC.svg","value":0},{"id":"q2_o3","text":"/images/visual/q2_optD.svg","value":0}]', 'q2_o2', '/images/visual/q2_prompt.svg', '[{"trait":"spatial","weight":1}]', 'grade_5_7', 'spatial', 'hard'),
('e94be24d-1567-47e5-82d8-d1bc5069a3b7', '8-10', 'aptitude', 'Complete the 3x3 logic matrix by determining the intersecting pattern rules.', '[{"id":"q3_o0","text":"/images/visual/q3_optA.svg","value":0},{"id":"q3_o1","text":"/images/visual/q3_optB.svg","value":0},{"id":"q3_o2","text":"/images/visual/q3_optC.svg","value":0},{"id":"q3_o3","text":"/images/visual/q3_optD.svg","value":0}]', 'q3_o1', '/images/visual/q3_prompt.svg', '[{"trait":"spatial","weight":1}]', 'grade_8_10', 'spatial', 'hard') ON CONFLICT (id) DO UPDATE SET 
test_id = EXCLUDED.test_id, type = EXCLUDED.type, question_text = EXCLUDED.question_text, options = EXCLUDED.options, correct_answer = EXCLUDED.correct_answer, image_url = EXCLUDED.image_url, mappings = EXCLUDED.mappings, cohort = EXCLUDED.cohort, category = EXCLUDED.category, difficulty = EXCLUDED.difficulty;